[build]
  command = "./netlify-build.sh"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PUBLIC_SITE_URL = "https://hidden-lotus.netlify.app"

[dev]
  command = "npm run dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 