import { Class } from '@/types'
import { IMAGES } from './images'

export type { Class }

export const classesData: Class[] = [
	{
		id: '1',
		name: 'Morning Vinyasa Flow',
		description: 'Start your day with an energizing vinyasa flow sequence.',
		longDescription:
			'Begin your day with this dynamic vinyasa flow class designed to energize your body and mind. This class combines breath-synchronized movement with strength-building poses to create a balanced practice that will leave you feeling refreshed and ready for the day ahead. Suitable for all levels with modifications provided.',
		instructor: 'Jaideep Pa',
		dates: ['2024-01-15', '2024-01-22', '2024-01-29'],
		time: '07:00 AM',
		duration: '75 minutes',
		price: '$25',
		categories: ['yoga'],
		level: 'beginner',
		maxParticipants: 20,
		equipment: ['Yoga mat', 'Blocks', 'Strap'],
		image: IMAGES.ICONS.HL_F_2,
	},
	{
		id: '2',
		name: 'Reiki Healing Session',
		description: 'Experience deep relaxation and energy healing.',
		longDescription:
			"Experience the gentle yet powerful healing energy of Reiki in this one-on-one session. Reiki is a Japanese energy healing technique that promotes stress reduction and relaxation while supporting the body's natural healing processes. This session includes a consultation, energy clearing, and chakra balancing.",
		instructor: 'Sarah Chen',
		dates: ['2024-01-16', '2024-01-23', '2024-01-30'],
		time: '02:00 PM',
		duration: '60 minutes',
		price: '$80',
		categories: ['reiki'],
		level: 'beginner',
		maxParticipants: 1,
		image: IMAGES.ICONS.HL_2,
	},
	{
		id: '3',
		name: 'Mindfulness Workshop',
		description: 'Learn practical mindfulness techniques for daily life.',
		longDescription:
			'Discover practical mindfulness techniques that you can integrate into your daily routine. This workshop covers breathing exercises, meditation practices, and mindful living strategies. Learn how to reduce stress, improve focus, and cultivate inner peace through simple yet effective mindfulness practices.',
		instructor: 'Dr. Michael Rodriguez',
		dates: ['2024-01-17', '2024-01-24', '2024-01-31'],
		time: '06:30 PM',
		duration: '90 minutes',
		price: '$35',
		categories: ['seminar', 'meditation'],
		level: 'beginner',
		maxParticipants: 15,
		image: IMAGES.ICONS.HL_3,
	},
	{
		id: '4',
		name: 'Cupping Therapy',
		description: 'Traditional cupping therapy for pain relief and wellness.',
		longDescription:
			'Experience the ancient healing art of cupping therapy, which uses suction cups to create negative pressure on the skin. This therapy helps improve blood circulation, relieve muscle tension, and promote healing. Perfect for those dealing with chronic pain, stress, or seeking deep relaxation.',
		instructor: 'Lisa Thompson',
		dates: ['2024-01-18', '2024-01-25', '2024-02-01'],
		time: '03:00 PM',
		duration: '45 minutes',
		price: '$60',
		categories: ['cupping', 'healing'],
		level: 'beginner',
		maxParticipants: 1,
		image: IMAGES.ICONS.LEAF_1,
	},
	{
		id: '5',
		name: 'Wellness Podcast Session',
		description: 'Join our wellness discussion and Q&A session.',
		longDescription:
			'Join us for an interactive wellness discussion where we explore various topics related to holistic health, mindfulness, and personal growth. This session includes expert insights, practical tips, and an open Q&A where you can ask questions about your wellness journey.',
		instructor: 'Jaideep Pa',
		dates: ['2024-01-19', '2024-01-26', '2024-02-02'],
		time: '07:00 PM',
		duration: '60 minutes',
		price: '$15',
		categories: ['podcast', 'seminar'],
		level: 'beginner',
		maxParticipants: 50,
		image: IMAGES.ICONS.MOR_1,
	},
	{
		id: '6',
		name: 'Evening Restorative Yoga',
		description: 'Gentle restorative poses for deep relaxation.',
		longDescription:
			"Wind down your day with this gentle restorative yoga class designed to promote deep relaxation and stress relief. Using props like bolsters, blankets, and blocks, you'll hold poses for extended periods to allow your body to fully relax and release tension.",
		instructor: 'Jaideep Pa',
		dates: ['2024-01-20', '2024-01-27', '2024-02-03'],
		time: '08:00 PM',
		duration: '75 minutes',
		price: '$25',
		categories: ['yoga', 'meditation'],
		level: 'beginner',
		maxParticipants: 15,
		equipment: ['Yoga mat', 'Bolster', 'Blanket', 'Blocks'],
		image: IMAGES.ICONS.HL_4,
	},
	{
		id: '7',
		name: 'Energy Clearing Session',
		description: 'Clear negative energy and restore balance.',
		longDescription:
			'Experience a comprehensive energy clearing session that removes negative energy and restores your natural energetic balance. This session combines Reiki, crystal healing, and intuitive energy work to help you feel lighter, more balanced, and energetically refreshed.',
		instructor: 'Sarah Chen',
		dates: ['2024-01-21', '2024-01-28', '2024-02-04'],
		time: '01:00 PM',
		duration: '90 minutes',
		price: '$95',
		categories: ['reiki', 'healing'],
		level: 'beginner',
		maxParticipants: 1,
		image: IMAGES.ICONS.MOR_2,
	},
	{
		id: '8',
		name: 'Stress Management Seminar',
		description: 'Learn effective stress management strategies.',
		longDescription:
			'Discover evidence-based strategies for managing stress in your daily life. This seminar covers the science of stress, practical coping mechanisms, and lifestyle changes that can help you build resilience and maintain emotional balance.',
		instructor: 'Dr. Michael Rodriguez',
		dates: ['2024-01-22', '2024-01-29', '2024-02-05'],
		time: '05:30 PM',
		duration: '120 minutes',
		price: '$40',
		categories: ['seminar'],
		level: 'beginner',
		maxParticipants: 25,
		image: IMAGES.ICONS.BG_1,
	},
	{
		id: '9',
		name: 'Deep Tissue Cupping',
		description: 'Intensive cupping therapy for deep muscle relief.',
		longDescription:
			'Experience deep tissue cupping therapy designed to target chronic muscle tension and pain. This intensive session uses stronger suction and longer duration to reach deeper muscle layers, providing relief for chronic pain conditions.',
		instructor: 'Lisa Thompson',
		dates: ['2024-01-23', '2024-01-30', '2024-02-06'],
		time: '04:00 PM',
		duration: '60 minutes',
		price: '$75',
		categories: ['cupping', 'healing'],
		level: 'intermediate',
		maxParticipants: 1,
		image: IMAGES.ICONS.HL_F_1,
	},
	{
		id: '10',
		name: 'Breathwork Masterclass',
		description: 'Master breathing techniques for health and vitality.',
		longDescription:
			'Learn powerful breathing techniques that can transform your health and vitality. This masterclass covers various breathwork practices including pranayama, box breathing, and breath of fire. Discover how proper breathing can improve energy, reduce stress, and enhance overall well-being.',
		instructor: 'Jaideep Pa',
		dates: ['2024-01-24', '2024-01-31', '2024-02-07'],
		time: '06:00 PM',
		duration: '90 minutes',
		price: '$30',
		categories: ['breathwork', 'meditation'],
		level: 'intermediate',
		maxParticipants: 12,
		image: IMAGES.ICONS.HL_F_3,
	},
]
